# Generated by Django 4.1 on 2022-09-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('PictureId', models.AutoField(primary_key=True, serialize=False)),
                ('PictureFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
